### ISSUE TITLE
Check that FW setup is minimal

### ISSUE THREAD

**Issue by zadigus** [jelasticozor/teamcity#8]
In the manifest, we are not sure that the following commands are really useful:

```yaml
  - closeFromOutsideWorld:
      nodeGroup: agents
      relatedNodeGroup: cp
  - closeFromOutsideWorld:
      nodeGroup: cp
      relatedNodeGroup: bl
```

Try to remove them and see if the environment still behaves properly.
