### ISSUE TITLE
Reliably setup the firewall rules on docker nodes (agents + cp)

### ISSUE THREAD

**Issue by zadigus** [jelasticozor/teamcity#9]
According to hidora:

"Les noeuds Docker ne sont pas configurable niveau firewall à travers le dashboard. La raison est simple, les noeuds utilisés habituellement sont des templates générés et maintenus par Virtuozzo. Les images Docker ne sont pas templatisées, il n'y a pas la "petite touche" Virtuozzo. Naturellement, leur prise en charge est donc moins bonne à travers le dashboard que les templates officiels.

Normalement, il faut aller configurer le firewall dans les images directement, à travers firewalld, iptables ou que sais-je. Ce qui me surprend c'est que tu aies réussi à générer des règles à travers l'API pour une image docker. C'est sûrement réalisable car tu as utilisé les nodegroups, mais je ne dirais pas que c'est fiable pour le coup. J'éviterais de me baser là-dessus car ce n'est pas une fonctionnalité qui a l'air prévue de base."

Therefore, using 

```yaml
- closeFromOutsideWorld:
      nodeGroup: agents
      relatedNodeGroup: cp
- closeFromOutsideWorld:
      nodeGroup: cp
      relatedNodeGroup: bl
```

should be replaced with proper, particular, firewall setup. Also, we should make [this function](https://github.com/jelasticozor/jelastic-common/blob/main/security/closeNodeGroupFromOutsideWorld.js) fail if the `nodeGroup` corresponds to nodes of type `docker`.
